### ISSUE TITLE
Bug: Frontmatter is duplicated in certain scenarios

### ISSUE THREAD

**Issue by TimKnight-DWP** [absolute-version/commit-and-tag-version#117]
**Describe the bug**
Depending on the format of the frontmatter on the CHANGELOG, commit-and-tag-version does not handle it correctly

**Current behavior**
Frontmatter is repeatedly duplicated at the top of the CHANGELOG

<img width="666" alt="image" src="https://github.com/absolute-version/commit-and-tag-version/assets/93127480/8efa6d40-1f76-438c-a306-c46e71b7a9c2">

**Expected behavior**
Frontmatter is retained and not duplicated

**Environment**

- `commit-and-tag-version` version(s): latest

**Possible Solution**

It'll be within the logic I added to: https://github.com/absolute-version/commit-and-tag-version/blob/master/lib/lifecycles/changelog.js#L25

**Additional context**
Raising this bug so everyone can have insight on it, I will synch my fork and work on a fix asap

**Comment by TimothyJones** [comment]
Awesome, thanks for the report, and the (upcoming) fix! Much appreciated!

**Comment by TimKnight-DWP** [comment]
If I run `npm run test:unit` using node 18.16.0, everything works as expected
If I run `npm run test:unit` using node 20.9.0, it all goes sideways

**Comment by TimKnight-DWP** [comment]
Will raise a separate issue for that

**Comment by TimKnight-DWP** [comment]
I cannot reproduce this bug natively using commit-and-tag-version - CLOSING may reopen if I find new data

**Comment by TimKnight-DWP** [comment]
For reference, this is likely coming about due to custom rules and post-event hooks within `.versionrc.js` on a specific repo, if it needs a specific fix here I'll come back, but suspect it's a local thing

**Comment by TimKnight-DWP** [comment]
Had FrontMatter defined in the "header"
```
 header:
    "---\nstatus: new\n---\n\n# Changelog\n\nAll notable changes to this product will be documented in this file.\n\n<!-- markdownlint-disable titlecase-rule -->",
```
within .versionrc.js

Which means it would have cut the FrontMatter out of the Changelog as per my code change and appended that and then the Header (containing Frontmatter as defined in versionrc), hence the duplication.

Probably a workaround prior to solving the bug fix.
