### ISSUE TITLE
Confusion around version bumps

### ISSUE THREAD

**Issue by Maelstromeous** [absolute-version/commit-and-tag-version#205]
Hello,

I have tested this package and commited with a message of `feat(repo): This should be a minor version` but upon running the command `commit-and-tag-version` it bumped it as a patch (0.0.1) instead of a minor (0.1.0).

Here is my package.json script:

```json
  "scripts": {
    "release": "commit-and-tag-version",
    "release-dry": "commit-and-tag-version --dry-run"
  },
```

I run the command via `pnpm run release`. I confirmed it also happens with `npm` as well.

I have no additional files that could be influencing the behaviour of the package.

**Comment by TimothyJones** [comment]
See the note at the end of the readme here:  https://github.com/absolute-version/commit-and-tag-version?tab=readme-ov-file#why-do-breaking-changes-before-100-not-trigger-a-100-release

Before version 1.0.0, semver has no opinion on what the numbers mean.

This tool follows the common convention of minor being a breaking change, and patch being for everything else (until you release 1.0.0, then it will follow semver).

**Comment by Maelstromeous** [comment]
Thank you for the insights, I totally missed that part of the readme! In terms of this package's issue, I'll close this off :)

**Comment by TimothyJones** [comment]
No worries! It’s a long readme, I should restructure it at some point
