### ISSUE TITLE
Custom Updater validation errors even when the updater runs correctly

### ISSUE THREAD

**Issue by TimKnight-Opencast** [absolute-version/commit-and-tag-version#27]
**Describe the bug**
When using custom updaters an error is shown despite logic running correctly

```  skip: {
    tag: true
  },
  tagPrefix: '',
  bumpFiles: [{
    filename: 'package.json',
    type: 'json',
  }, {
    filename: 'templates/print-toolbox-version.yml',
    updater: {
      readVersion: (contents) => contents.match(/VERSION:\s*(\d.*)/gm),
      writeVersion: (contents, version) => contents.replace(/VERSION:\s*(\d.*)/gm, `VERSION: ${version}`),
    }
  }]```

**Current behavior**
results in errors like this:

```
Unable to obtain updater for: {"filename":"templates/print-toolbox-version.yml","updater":{}}
 - Error: Unsupported file (templates/print-toolbox-version.yml) provided for bumping.
 Please specify the updater `type` or use a custom `updater`.
 - Skipping...
```

But the custom updater is actually run and the relevant files get updated correctly

**Expected behavior**
When custom updaters are valid syntax (and therefore run correctly anyway) - No error should be displayed in CLI

**Additional context**
We think it was this commit that broke things which doesn’t seem to take into account the option of specifying an object for updaters when it’s doing its validation checks: https://github.com/conventional-changelog/standard-version/commit/2785023c91668e7300e6a22e55d31b6bd9dae59b

**Comment by TimothyJones** [comment]
Which version are you using?

**Comment by TimKnight-Opencast** [comment]
at the moment v9.5.0 of standard-version main @TimothyJones 

But we will probably look to move to this one since you seem to be active, and we have an Open Source team at Opencast who also might look to help raise MRs for contributions and fixing issues on the main

**Comment by TimKnight-Opencast** [comment]
Sorry I have literally just been shown the release notes with the fix applied DOH
