### ISSUE TITLE
Major bump doesn’t happen until version 1.0.0

### ISSUE THREAD

**Issue by jjroth** [absolute-version/commit-and-tag-version#46]
Major bumps don’t seem to happen until version 1.0.0. 

Looks like this is an open issue on standard-version. 

https://github.com/conventional-changelog/standard-version/issues/848

**Current behavior**
If my package version is 1.0.0 and a breaking change commit is made then running commit-and-tag-version returns 2.0.0 as expected. 

However, if my package version is 0.0.1 and a breaking change commit is made then running commit-and-tag-version returns 0.1.0. 

Is this expected? It surprised me. If it is an issue then it is likely and issue in either dependency conventional-recommended-bump or the way that it is configured in this project. 

**Expected behavior**
I would expect that any commit with “BREAKING CHANGE:” in a commit’s message would always result in a bump to the Major version. 

**Environment**

- `commit-and-tag-version` version(s): v10.1.0

- Node/npm version: Node 14.17.4/npm 6.14.15
- OS: Windows 10

**Possible Solution**

Tried to have a look but I’m not familiar with the code see.

**Comment by TimothyJones** [comment]
Yes, this is expected. The tl;dr is that semver doesn’t give any guarantees of meaning below 1.0.0, and the convention that npm and other ecosystems seem to have settled on (without a spec) is that below 1.0.0 minor is breaking, and patch is everything else. See [this comment](https://github.com/absolute-version/commit-and-tag-version/issues/26#issuecomment-1155303502) for some discussion.

This is the second time today that this has come up- and frankly it surprised me too when I was first using standard-version.

I think it is worth adding a FAQ that explains this.

**Comment by jjroth** [comment]
Thanks @TimothyJones, I’ve had a closer look at the semver specification and you’re absolutely right!

Definitely worth adding to an FAQ. 

Thanks for the quick response.

**Comment by TimothyJones** [comment]
Finally added the FAQ in this commit: https://github.com/absolute-version/commit-and-tag-version/commit/bc6f792bcb72b17d912a17f3927fba3ecf297492

Thanks again for raising.
