### ISSUE TITLE
npm run release -- --release-as 1.0.0 as first release ends up with 1.1.0

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [absolute-version/commit-and-tag-version#51]
**Describe the bug**
npm run release -- --release-as 1.0.0 as first release ends up with 1.1.0. Maybe I'm missing something but I thought I would get 1.0.0 and not 1.1.0.

**Current behavior**
After running npm run release -- --release-as 1.0.0 as the first ever release, the tag ends up as 1.1.0.

**Expected behavior**
After running npm run release -- --release-as 1.0.0 as the first ever release, the tag ends up as 1.0.0.

**Environment**

- "commit-and-tag-version": "^10.1.
- Node/npm version:  18.12.1/8.13.2
- OS: Win10 64bit

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable
![Code_15_22-49-22JNpFnmtd3j](https://user-images.githubusercontent.com/110549389/212569077-e64b6313-7a96-4e4c-a7a0-da20a945e1a9.png)

Maybe this is not how you're supposed to use commit-and-tag-version so I'm open for any solutions. 😄

**Comment by TimothyJones** [comment]
Hmm. This is unexpected.

What is the `nr` command you’re running there? I’m not familiar with it.

What happens if you remove that tag and commit and do:

`npx commit-and-tag-version --dry-run --release-as 1.0.0`

(note no double `-` before the arguments)

Are there any tags in this repository already?

**Comment by henrikvilhelmberglund** [comment]
`nr` is the run alias in https://github.com/antfu/ni so basically the same as npm run.

I tested `nr release --dry-run --release-as 1.0.0` and it tagged 1.0.0 as expected so I guess my problem was the extra `--`. I think I copy pasted those from the README.

Is there a reason for the extra `--` or is it safe to omit them?

**Comment by TimothyJones** [comment]
You need those with `npm run`, so my guess is that `nr` isn’t really an alias for `npm run`

**Comment by TimothyJones** [comment]
You're welcome! Glad it got fixed!
