### ISSUE TITLE
How can I have this package run `pnpm i` before committing?

### ISSUE THREAD

**Issue by AlexAegis** [absolute-version/commit-and-tag-version#62]
After a version bump, all the version specifiers in the pnpm lockfile have to be updated (by running `pnpm install`). If not, frozen-lockfile installs will fail, which `pnpm` does automatically when invoked in a ci environment.

```yml
      - name: install
        run: pnpm install
```

![image](https://user-images.githubusercontent.com/16900547/229720580-fc5b82f3-49bf-41bf-9a21-646860ec045d.png)

This results in me having to amend the commit, recreate the version tag, or if I forget it, notice the error way later and push the fix later:

![image](https://user-images.githubusercontent.com/16900547/229720712-2367ab3f-9e79-4559-9b98-f59c84fabd3e.png)

**How can I tell `[commit-and-tag-version](https://github.com/absolute-version/commit-and-tag-version)` to run a `pnpm i` right before committing to always have a fresh lockfile?**

**Comment by TimothyJones** [comment]
Use a lifecycle script- probably precommit. See the [documentation here
](https://github.com/absolute-version/commit-and-tag-version#lifecycle-scripts)

**Comment by AlexAegis** [comment]
Thank you! Now that you say it, it's really obvious, should've thought of it sooner 🤦

**Comment by AlexAegis** [comment]
Well this was a tiny bit more involved than I first thought, I leave this here for future reference in case anyone finds themselves in the same situation:

`pnpm` does not run pre-post- script by default for a while now. You can enable them but if you already have `husky` you can just add `pnpm i` to a git hook. That alone isn't enough, you also have to stage the fresh lockfile, so your `pre-commit` hook will look something like this:

```sh
#!/bin/sh

pnpm install
git add pnpm-lock.yaml
npx lint-staged
```

And that solves my problem, the commit does contain the fresh lockfile, but after the commit is created it leaves the workspace in a weird state where the staged version of the lockfile is a change reverting it to the previous version, and then there's another unstaged change with the update.

![image](https://user-images.githubusercontent.com/16900547/229738182-7de6de39-2268-4b8a-8d56-2629e2cf8f40.png)

> For example when bumping from `0.0.5` to `0.0.6`, the commit will contain `0.0.6`, that staged change will contain `0.0.5` and the unstaged change contains `0.0.6`

`git add`-ing the unstaged change will cancel the staged one. You can solve this but automating this part too with a `post-commit` hook:

```sh
#!/bin/sh

git add pnpm-lock.yaml
```

This feels hacky, but I have no idea what may cause this.

```sh
git 2.40.0
pnpm 8.1.1
node 19.8.1
commit-and-tag-version 11.2.0
lint-staged 13.2.0
husky 8.0.3
```

**Comment by TimothyJones** [comment]
The link is to the readme for this repository. There should be no need to muck about with husky or whatever (although you might need to turn it off for that commit if you're using it - depending on how you're using it). 

You might also be interested in the `--commit-all` flag, which commits all changes, so you don't have to manually stage. That's also documented in the readme, see [here](https://github.com/absolute-version/commit-and-tag-version#committing-generated-artifacts-in-the-release-commit)

**Comment by AlexAegis** [comment]
Yes I'm guilty of that, the moment I saw 'precommit' and 'It supports lifecycles'  I was thinking of npm/git hooks. I'll try out the real deal later today. Sorry for not paying attention!

**Comment by TimothyJones** [comment]
No worries at all. Glad you got something that works 😎
