### ISSUE TITLE
Show commits in changelog even if they don't follow format

### ISSUE THREAD

**Issue by felixvd** [absolute-version/commit-and-tag-version#71]
Pretty simple usage question, but is there a way to show commits that don't follow the `conventionalcommits` format? It would be convenient if they appeared under e.g. an "Other" heading.

**Comment by TimothyJones** [comment]
Not as far as I'm aware, sorry.

From a quick glance at the [conventional-changelog-config-spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.2.0/README.md) I don't see a way to do this, but that doesn't mean it isn't possible with some option.

Following the [fork rationale](https://github.com/absolute-version/commit-and-tag-version/discussions/30), this might be a little outside the remit, but I'd be happy to expose anything that you can make the conventional-commit related dependencies do.

**Comment by felixvd** [comment]
Thanks for the quick response. [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) adds the commits without sections if no preset is set, so 

I'm guessing the undefined types are discarded [here](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/writer-opts.js#L100). Is there a way to define `writerOpts.transform`  in the `package.json`, or use a custom preset? I'm not very experienced with JS so I'm stabbing in the dark.

**Comment by TimothyJones** [comment]
You can use a custom preset with the `preset` option - which I believe you can set on the command line or in the package json like this:

```
{
  "commit-and-tag-version": {
    "preset": "alternative-preset-name"
  }
}
```

**Comment by TimothyJones** [comment]
Looking at the code, I think it will treat `preset: ""` as no preset, and then override it with the default. So you might have to figure out which preset will do what you want.

**Comment by TimothyJones** [comment]
I'll close this for now. Please feel free to reopen (or make another issue) if you have any further questions
