### ISSUE TITLE
Changes between tags with no changes

### ISSUE THREAD

**Issue by konclave** [absolute-version/commit-and-tag-version#76]
I have a monorepo with several applications in it and I'm trying to implement the separate version bump and changelog for each application. 

Each app has a config file in it root folder and I run `commit-and-tag-version` in each app folder and set the tag with the app prefix. 
That is the config: 
```js
{
    path: '.',
    'tag-prefix': `${appName}.v`,
    releaseCommitMessageFormat: `chore(release): ${appName}@{{currentTag}} [skip ci]`,
}
```

But if I run `commit-and-tag-version` with --dry-run right for the second time with no any changes accept version bump and changelog, then I see in changes a link to the repo with changes set between tags like:
```
---
## [1.1.1](https://github.com/..../compare/app.tag.v1.1.0...app-tag.v1.1.1) (2023-05-03)
---
```

Why are changes not empty? I expected to see nothing there and use that to determine if I need to bump version for the app or not.

**Comment by TimothyJones** [comment]
I'll close this as there's no response, and I _think_ your request is covered by #43.

Please feel free to reopen if you need further clarification, or if your question isn't covered by that issue.
