### ISSUE TITLE
How to retrieve the generated CHANGELOG part (only the latest changes) in lifecycle scripts

### ISSUE THREAD

**Issue by davidsneighbour** [absolute-version/commit-and-tag-version#88]
I am aware of #38, but I can't see how this can be helpful for my special use case. After the tag is created, I would like to create a release on GitHub via REST API. 

The script to clear probable questions:

```bash
# create a release on GitHub
GITHUB_REPO=https://github.com/${GITHUB_REPOSLUG}
URL="$GITHUB_REPO"/"releases/edit/v""$VERSION"
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: token ${GITHUB_SECRET}" \
  https://api.github.com/repos/"${GITHUB_REPOSLUG}"/releases \
  -d "{\"tag_name\":\"v${VERSION}\",\"name\":\"v${VERSION}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":true}"
xdg-open "${URL}" &>>/dev/null
```

The `body` value in the payload could contain the list of changes. 

Is there an easy way to obtain the changelog changes at some point or do I have to create a post-changelog-creation hook that takes a diff of the changelog into a temporary file to reuse later on? That would be my current idea to implement this.

Thanks for any suggestions.

**Comment by 98christianp** [comment]
Did you figure a solution to your problem?

**Comment by davidsneighbour** [comment]
no, sorry.

**Comment by TimothyJones** [comment]
(I wrote this before I forked commit-and-tag-version)

**Comment by Houtheyfa** [comment]
@davidsneighbour check this thread: https://github.com/conventional-changelog/standard-version/issues/610#issuecomment-683337506

The idea is to save the output in a different file other than the Changelog.md, then pass it to your API call.
`standard-version -i RELEASE_BODY.md --skip.commit [other options]`

**Comment by davidsneighbour** [comment]
I am closing this and recommend reading the link by @Houtheyfa. 

The following two lines in my prerelease hook create a file `changes.md` with the changelog:

```bash
RELEASE_NOTES="$(npx commit-and-tag-version --dry-run | awk 'BEGIN { flag=0 } /^---$/ { if (flag == 0) { flag=1 } else { flag=2 }; next } flag == 1')"
echo "${RELEASE_NOTES}" >changes.md
```

The curl call in the original issue text is working only if the changes are not too large, else I have to add the text in changes.md manually to the release.
